baseURL = "https://sun-xiaoxu.github.io"
title = "Goldydocs"  # 不知道你是哪里的
enableRobotsTXT = true
theme = ["docsy"]
enableGitInfo = true

#语言设置
contentDir = "content/zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true
[languages]
[languages.zh]
title = "猴子的博客"  #  浏览器和左上角的名字
description = "A Docsy example site"
languageName ="中文"
weight = 1
disableKinds = ["taxonomy", "taxonomyTerm"]


	

# 高亮配置
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"


[params]
copyright = "孙晓旭"
privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

version_menu = "Releases"
archived_version = false
version = "0.0"
url_latest_version = "https://example.com"

# 点击编辑后跳转到远程仓库修改博客
github_repo = "https://github.com/sun-xiaoxu/docsy-example"
github_project_repo = "https://github.com/sun-xiaoxu/docsy"

#如果内容目录不在repo的根目录中，请在此处指定其他远程仓库地址
# github_subdir = ""

# 谷歌自定义搜索引擎ID。删除或注释掉以禁用搜索
#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# 启用Algolia DocSearch
algolia_docsearch = false
# 启用 Lunr.js 离线搜索
offlineSearch = true

# 代码块上启用语法高亮显示和复制按钮
prism_syntax_highlighting = true

# 用户界面配置
[params.ui]
# 启用以在压缩状态下显示侧栏菜单。
sidebar_menu_compact = false
#  设置为true可禁用面包屑导航。
breadcrumb_disable = false
# 设置为true以隐藏侧栏搜索框（如果启用搜索，顶部导航搜索框仍将显示）
sidebar_search_disable = false
# 设置logo
navbar_logo = false
# 设置为true可禁用网站页脚中的“关于”链接
footer_about_disable = true

#用户反馈
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# 显示页面预计阅读完花费的时间
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://example.org/twitter"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://example.org/stack"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/google/docsy"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://example.org/slack"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"

